### ISSUE TITLE
Designers video is not full width on desktop

### ISSUE THREAD

**Issue by cmata23x3** [DesignOpen/designopen.github.io#138]

**Comment by terracomma** [comment]
Are there any more details about this issue?

**Comment by GarthDB** [comment]
It is something we are fixing, but the blend find video isn't going full width. We're fixing it now.

**Comment by terracomma** [comment]
The video on this page?
http://designopen.org/blogging_about/designers-can-open-source-session-video/

(I wasn't sure what video we were talking about, the issue title was pretty vague)

**Comment by cmata23x3** [comment]
Yeah that one. Sorry about the bad description.

**Comment by cmata23x3** [comment]
:+1: done
