### ISSUE TITLE
Create personas

### ISSUE THREAD

**Issue by alicjasalamon** [DesignOpen/designopen.github.io#143]
It would be nice to create legitimate personas to be aware what would convince users to contribute to open source projects and what is the best way to teach them how to do that.

Sketch of possible personas:
1. 	Designer who wants to contribute, knows how to do this, he is just looking for interesting projects
2. 	Designer who wants to contribute, but has no idea how to contribute and is looking for instructions in simple language
3. 	Designer who doesn't want to contribute, but maybe he may be convinced. By what?
4.     Novice designer who wants to build his portfolio by contributing to open source projects.
5.	Programmer who is contributing to open source projects, but wants to know about design. 

Interviews and surveys should be conducted to gather necessary data.

**Comment by una** [comment]
I think #2 is the biggest persona.

Also consider:
Programmer who manages/contributs to an open source project and wants designer contribution

**Comment by winterdamsel** [comment]
'Personas' have been created and will be added to the Articles section.

**Comment by GarthDB** [comment]
Sweet - we could also start a [wiki](https://help.github.com/articles/about-github-wikis/); it's a great way to document things for potential contributors.

**Comment by jdittrich** [comment]
Great. Is/will there be any documentation how the personas were created?

**Comment by winterdamsel** [comment]
Not yet but we can create a short document for it :)

**Comment by jdittrich** [comment]
:+1:

**Comment by winterdamsel** [comment]
Link with preliminary personas https://docs.google.com/document/d/1fgk5nsTAuvdqW3GjaTF69obr1QmB9LYnUM62CFHZfAU/edit?usp=sharing
