### ISSUE TITLE
Correct names for categories in Resources section

### ISSUE THREAD

**Issue by alicjasalamon** [DesignOpen/designopen.github.io#147]
After introducing categories instead of tags in Resources section (issue https://github.com/DesignOpen/designopen.github.io/issues/144) now new set of categories that actually make sense should be prepared.

**Comment by winterdamsel** [comment]
Can we also add categories for Articles? Or tags.
Current proposals for categories in Articles are:
*About*, those that explain the purpose and efforts regarding the initiative.
*Tutorial/FAQ*, posts with instructions on how to install things.
*Life events*, if someone went to a conference or event
*Inspirational thoughts*, probably there'll be less kittens with that title.
