### ISSUE TITLE
CONTIBUTING.md

### ISSUE THREAD

**Issue by GarthDB** [DesignOpen/designopen.github.io#150]
We should probably make some [contributing guidelines](https://help.github.com/articles/setting-guidelines-for-repository-contributors/).

**Comment by una** [comment]
Great writeup for writing PR's: https://github.com/blog/1943-how-to-write-the-perfect-pull-request

**Comment by una** [comment]
Similar to #194

**Comment by GarthDB** [comment]
Aaaaaaand done.
