### ISSUE TITLE
Adding categories for articles

### ISSUE THREAD

**Issue by winterdamsel** [DesignOpen/designopen.github.io#151]
It would be useful to also add categories in Articles, since they are starting to become a bit scattered. 
Current proposals:
**About**, those that explain the purpose and efforts regarding the initiative.
**Tutorial/FAQ**, posts with instructions on how to install things.
**Life events**, if someone went to a conference or event
**Inspirational**, probably there'll be less kittens with that title.

**Comment by GarthDB** [comment]
This is done now right @winterdamsel?

**Comment by winterdamsel** [comment]
The articles are sorted but I believe we haven't added the proper tags/categories in the blog posts.

**Comment by GarthDB** [comment]
Open it back up if you're think to work on it. Should we use the same categories as resources? @winterdamsel @alicjasalamon

**Comment by winterdamsel** [comment]
Would the Articles section be then like a magazine? Then it would make sense to have categories instead of tags.

**Comment by alicjasalamon** [comment]
Or if Articles are more like a blog then just sort them by date (and eventually add tags)
