### ISSUE TITLE
Check design survey questions

### ISSUE THREAD

**Issue by jdittrich** [DesignOpen/designopen.github.io#160]
http://m18.uni-weimar.de/pad/p/ossdesignersurvey

- [x] Add new questions (if you know any) for sections "2) Cooperation"
- [x] Add new questions (if you know any) f  3.1. Exposure of finished works
- [ ] "Clean up" sections with many question, which may ask twice for the same.
- [ ] Redirections page Address for sending your experiences
- [ ] Redirections page interesting Links/Projects on/with Open Source Design. Suggestion: [resources](https://github.com/DesignOpen/designopen.github.io/issues/160)

**Comment by winterdamsel** [comment]
Draft can be located at https://docs.google.com/document/d/1To1mN-OvQnjP8w9fdVj6CzvPsLJIGbHzgFLhoMKtXzQ/edit?usp=sharing
