### ISSUE TITLE
Create Developer Survey

### ISSUE THREAD

**Issue by jdittrich** [DesignOpen/designopen.github.io#161]
GOAL: 
- Cooperation of devs with Designers: Methods, Problems
- How do they think about design/usability/UX and what do they do about it

- [x] setup structure
- [x] talk to developers/open-question-interviews
- [x] create first questions
- [x] finish analysis
- [x] review questions
next: proto survey

**Comment by GarthDB** [comment]
@winterdamsel @alicjasalamon @jdittrich would you say this is done? The talk to developers is pretty much completed.

**Comment by jdittrich** [comment]
we are currently analysing the interviews, so it is still in progress.

**Comment by winterdamsel** [comment]
Reanalysing >_< Created a new Trello board for it @GarthDB https://trello.com/b/pFDEaruQ

**Comment by winterdamsel** [comment]
Draft of survey can be found @ https://docs.google.com/document/d/1To1mN-OvQnjP8w9fdVj6CzvPsLJIGbHzgFLhoMKtXzQ/edit?usp=sharing
