### ISSUE TITLE
center content of the homepage on wide screens

### ISSUE THREAD

**Issue by alicjasalamon** [DesignOpen/designopen.github.io#166]
Text on the homepage is not centered when screen width > 1400px ![image](https://cloud.githubusercontent.com/assets/3893215/6202781/41ce54a0-b505-11e4-91cb-6581675dc2c4.png)

**Comment by GarthDB** [comment]
@alicjasalamon you self assigned this, are you working on it?

**Comment by alicjasalamon** [comment]
I've just finished :)

**Comment by GarthDB** [comment]
https://github.com/DesignOpen/designopen.github.io/pull/168
