### ISSUE TITLE
Home page not updating "Recent Articles"

### ISSUE THREAD

**Issue by winterdamsel** [DesignOpen/designopen.github.io#179]
The last submission, "A call for help", does not come up in the "Recent Articles" section. It does show up when we navigate to the All-articles page.

**Comment by lauweijie** [comment]
That caught my attention too, but looking at the source, only articles with "featured" as one of the tags get displayed in the "Recent Articles" section on the home page.

**Comment by winterdamsel** [comment]
Mm...I think there's something else because other articles that are a bit older have that same tag but are not being displayed there.
