### ISSUE TITLE
List your Slack channel on your website

### ISSUE THREAD

**Issue by bnvk** [DesignOpen/designopen.github.io#195]
A few ppl in the IRC room have mentioned you have a Slack channel where most of the people in this channel have migrated to instead of being in #opensourcedesign

It'd be swell if that was listed on your website how to join / participate in the Slack thread.

**Comment by GarthDB** [comment]
That's the downside to Slack, it doesn't have a simple way for non-members to add themselves, or even ask to join. I've reached out to them to see what we can do.

Until something gets implemented on Slack's side, I have Gitter setup and linked in our read me. I get notifications when activity happens, but not much happens there.

Most real conversation happens in our GitHub issues. Our slack team is really only being used for casual conversation - when things get serious we move it out to GitHub.

Any recommendations on what more we could do @bnvk?

**Comment by GarthDB** [comment]
how about this https://github.com/DesignOpen/designopen.github.io/pull/197

**Comment by GarthDB** [comment]
I closing this since I think it is resolved with the google form.

**Comment by bnvk** [comment]
@GarthDB thanks for adding this to the readme- definitely an improvement as I was able to figure out how to ask to be added. I guess it still feels strange not being listed on the website. Reason being, if the goal of this is to be an "open" community, then showing all methods to engage in conversation should be easy, no? I get that you're saying that's what Gitter is for, but every time I've opened that up there's no conversation or backlog or anything, which is why I filed this issue!

However, if your goal is to be about "open source" and "design for open source" but *not* be an "open organization" then keeping your Slack closed and harder to is definitely a good call as smaller private chats are often less noisey + more productive. The later point is something I'm interested in (open organization structures), but maybe we just have very different goals with OSD, which is totally cool either way :smile:

**Comment by GarthDB** [comment]
@bnvk we could add the instructions for requesting a slack invite to the main page. I'm not against it if we can find a good place for it.

The goal is to be an open community (without quotes) and I'm happy to show all methods to be engaged.

I just broke the ice and made the first post on Gitter. It has some great potential, but it's not the tool any of the existing contributors are using. 

At this point in the project, I just want to keep the momentum, so I will use whatever tools people are using, and right now that seems to be Slack. Many contributors, FEDs, and designers are using Slack for work so it is a natural fit. I can't open the Slack team; I've asked about it and it is not currently supported. Until that feature is added, or we move to something else we will have to settle for the google form. The goal is not to add everyone

I do think we have some differing goals and/or audiences with our projects, but we are happy to work together.

**Comment by bnvk** [comment]
@GarthDB cool cool. I fully get the point of using Slack for all the reasons you mention. I've been exploring various IRC themes and they're all a bit of work and, well open source collaborations take time... hehe :smile:

That said, using Slack, you might want to check out http://rauchg.com/slackin/ as it was made the bridge this gap of "opening" up Slack quite well I think.

**Comment by GarthDB** [comment]
oh, very cool. That could be exactly what we are looking for.

**Comment by simonv3** [comment]
Just as a side note, at OpenFarm we're playing around with this Slack-IRC channel communicator. It was very easy to set up: https://github.com/ekmartin/slack-irc.

You just point it at a channel within your slack, and at a channel on an IRC channel, and things get sent back and forth. Only downside is that if everyone is on Slack who's part of your permanent team, your IRC channel looks pretty empty.

**Comment by GarthDB** [comment]
Very interesting. What about trying to ping one person in particular in slack from the IRC?
It doesn't seem like that would be possible.

**Comment by simonv3** [comment]
No I don't think so :(
