### ISSUE TITLE
Re/Structure website Sass content

### ISSUE THREAD

**Issue by verpixelt** [DesignOpen/designopen.github.io#200]
As I've already talked with @una on Twitter https://twitter.com/Una/status/580506322908659712 this is the first issue for the re/structuring Sass files topic.

I would just like to start with the _todo.scss file and split the containing content into the appropriate Sass partials. During this task I may also clean up a bit (combine duplicated styles, write the declaration more readable, etc).

If this is something which would work for you please give me a "go!" ;)

**Comment by una** [comment]
sounds goos @verpixelt :) could definitely use some refactoring!

**Comment by GarthDB** [comment]
Excellent @verpixelt. Let us know if we can help.

**Comment by GarthDB** [comment]
Hey @verpixelt, do you want to call this finished?

**Comment by verpixelt** [comment]
Hey @garthdb, no not yet. Sry I'm a bit swamped with stuff right now.

**Comment by GarthDB** [comment]
@verpixelt no need to apologize. I knew you made a pull request and wanted to see if that covered what you wanted to do with this.

If you need any help let us know.

**Comment by GarthDB** [comment]
@ttimsmith has already started some of this and we added scss_lint to help out.
