### ISSUE TITLE
Getting rid of rem as font-sizing unit

### ISSUE THREAD

**Issue by verpixelt** [DesignOpen/designopen.github.io#201]
Sizing type with `rem` makes responsive adjustments more rigid. `rem` doesn't scale well. You're only able to size elements on a root based level. I propose to shift to `em`s. This gives the opportunity to scale type on a more modular level.

**Comment by GarthDB** [comment]
I recommend we stay with rems if we are looking for modularity. Ems can compound on each other so doing work on a specific element requires the developer to find all the places font size has been adjusted in the Dom lineage, while rems remain universal to the root regardless of the rest of the elements' settings.

If you can find a compelling case in our project to use ems instead let me know.

**Comment by GarthDB** [comment]
I'm closing this for now, @verpixelt if you want to reopen, feel free.

**Comment by verpixelt** [comment]
@GarthDB yeah, sure! Will get back to you in a few days ;)
