### ISSUE TITLE
Can designerbot please stop posting to the #opensourcedesign channel on freenode?

### ISSUE THREAD

**Issue by pdurbin** [DesignOpen/designopen.github.io#205]
As [requested](https://botbot.me/freenode/opensourcedesign/msg/34037570/) [a few](https://botbot.me/freenode/opensourcedesign/msg/34351826/) [times](https://botbot.me/freenode/opensourcedesign/msg/34924910/) in the freenode #opensourcedesign channel, can designerbot please stop posting there? Thanks!

![irc_logs_for_ opensourcedesign_botbot me_ o_o _-_2015-03-27_21 51 40](https://cloud.githubusercontent.com/assets/21006/6879450/e31a8f46-d4cb-11e4-837c-64501d93b888.png)

**Comment by GarthDB** [comment]
Sorry, I haven't been in the IRC lately.

I've removed the github/irc hook. If you still have issues let me know @pdurbin.
