### ISSUE TITLE
Setup Twitter Card page data

### ISSUE THREAD

**Issue by GarthDB** [DesignOpen/designopen.github.io#206]
We should setup a default twitter card data and encourage custom twitter cards for custom article designs.

https://dev.twitter.com/cards/types

**Comment by michaelck** [comment]
Just a note: it looks like the "default twitter card" portion of this issue was addressed with your commit on April 28th: https://github.com/DesignOpen/designopen.github.io/commit/5d65358661e1a080fdd537e8a7e3087ef13a1569

**Comment by GarthDB** [comment]
Good call. More work to do, but we should close this one. Thanks @michaelck

**Comment by michaelck** [comment]
No problem! I just happened to be looking for an issue to contribute to. Feel free to tag me on similar tasks to this one.
