### ISSUE TITLE
Setup Slackin

### ISSUE THREAD

**Issue by GarthDB** [DesignOpen/designopen.github.io#210]
[Slackin](http://rauchg.com/slackin/) seems like a perfect fit for our team.

The recommendation came from @bnvk in https://github.com/DesignOpen/designopen.github.io/issues/195#issuecomment-88483601

**Comment by terracomma** [comment]
This looks like the coolest thing. I like opening up Slack as much as possible.

**Comment by lauweijie** [comment]
I could help set this up, but I'll need a slack API token that has permission to invite users.

https://osd-slackin.herokuapp.com/

**Comment by GarthDB** [comment]
@lauweijie finished it already.
