### ISSUE TITLE
Allow @OpenSourceDesign to use @DesignOpen logo

### ISSUE THREAD

**Issue by bnvk** [DesignOpen/designopen.github.io#211]
Both communities have differing core contributors and some differing ideas and immediate goals. However, both communities seem to be ultimately working towards the same larger goal of "bringing great design to open source software" thus I am asking on behalf of the @opensourcedesign portion to use the wonderful logo created @DesignOpen folks

There is concern about *how* our group might use the logo. However, a good discussion occurred in the OSD Slack group where it seemed there was consensus!

I think @terracomma said it quite well `"I'm on board with all that then do you think we could name it something other than mark or logo to encourage people to remix it? if we called it the "symbol" or "icon" would designers be less precious with it? i just know so many who don't manipulate logos out of principle"`

I'm just opening this issue for posterity and because @GarthDB asked me to pre-conversation

**Comment by jdittrich** [comment]
[Related](https://github.com/opensourcedesign/resources/issues/14)

**Comment by jdittrich** [comment]
I suppose, yes, people are more likely to modify an icon. e.g. one always reads in CI-Guides that it is a major offence to change a *logo*

**Comment by jancborchardt** [comment]
It would really be cool to have it as a more general icon. Similar to how it is derived from the open source icon, just like the open hardware icon etc.

**Comment by jdittrich** [comment]
To ease understanding, these are the logos @jancborchardt refereed to:
![opensource](https://cloud.githubusercontent.com/assets/3416487/6964778/b8a772e4-d94c-11e4-985d-996ebe2ea7fa.png) ([source](http://en.wikipedia.org/wiki/File:Opensource.svg), [CC BY 2.5](http://creativecommons.org/licenses/by/2.5/deed.en))
![open-source-hardware-logo svg](https://cloud.githubusercontent.com/assets/3416487/6964780/bc29c49e-d94c-11e4-9e14-114674dc4c26.png)([source](http://de.wikipedia.org/wiki/Freie_Hardware#/media/File:Open-source-hardware-logo.svg), Public Domain)

**Comment by bnvk** [comment]
Looks like the folks at Open Annotation had a similar idea to much success

![open anontation](https://cloud.githubusercontent.com/assets/48677/7255589/73f0212a-e84a-11e4-9696-0728b472bbee.png)

Speaking of @GarthDB did you want to follow up with any terms / conditions on this thread? I'm about ready to throw together a design for our splash page and am planning on using your nifty icon!

Close this issue if yay and you've had your say :smile:

**Comment by gillisig** [comment]
:+1: I think this is a great idea!

**Comment by bnvk** [comment]
As per [this comment](https://github.com/opensourcedesign/jobs/issues/26#issuecomment-96839125) by  the DesignOpen icon has been removed from the OpenSourceDesign.net site. I'm closing this issue as this is no longer something I want to pursue or try using.
