### ISSUE TITLE
differences designopen/opensourcedesign

### ISSUE THREAD

**Issue by jdittrich** [DesignOpen/designopen.github.io#212]
I contribute to both [DesignOpen](https://github.com/DesignOpen) and [OpenSourceDesign](https://github.com/opensourcedesign). There seem to be significant overlaps in regards to contributors and goals. 

I wonder in which regards the both projects differ/are similar – are there important "ideological"  differences? A sort of segmentation towards different aspects (like DesignOpen focusing on sharing process and OpenSourceDesign focussing on Designers Contributions to Open Source Software)?

Related: #211 and the [almost-the-same-question](https://github.com/opensourcedesign/resources/issues/14) in a subrepo of OpenSourceDesign

**Comment by GarthDB** [comment]
I commented on [this issue](https://github.com/opensourcedesign/resources/issues/14) since I think its the most likely to have more participants.

**Comment by GarthDB** [comment]
I think it was well answered, closing unless we need to reopen.

![image](https://cloud.githubusercontent.com/assets/125516/14937775/1591cc44-0ecf-11e6-9848-31e7aa994e20.png)
