### ISSUE TITLE
"Designers can open source session video" article page broken

### ISSUE THREAD

**Issue by verpixelt** [DesignOpen/designopen.github.io#230]
The page looks a bit broken to me =/
Can't rebuild it locally though. It looks like the content gets injected twice before the actual article tag.

![design-open](https://cloud.githubusercontent.com/assets/1640079/7389238/69d347e4-ee6c-11e4-924e-8eead9b5784a.png)

**Comment by GarthDB** [comment]
Hey @verpixelt thanks. I broke it yesterday with adding twitter card support.

https://github.com/DesignOpen/designopen.github.io/pull/231 will fix it.

**Comment by GarthDB** [comment]
fixed https://github.com/DesignOpen/designopen.github.io/pull/231
