### ISSUE TITLE
Move to OpenDesign.Foundation

### ISSUE THREAD

**Issue by GarthDB** [DesignOpen/designopen.github.io#240]
Changing our url. I'll set up redirects, but if I miss anything from the previous site, let me know.

**Comment by GarthDB** [comment]
Things to change/update:
- [ ] gh-pages cname
- [ ] GitHub org (no idea what the new one should be; maybe I'll contact [opendesign](https://github.com/opendesign) to see if they are open to handing it over)
- [ ] Resource collector url (is this worth doing a subdomain on opendesign.foundation for this @cmata23x3 @lauweijie ?)
- [ ] Look at getting a trademark for Open Design, and look at getting the twitter handle.

**Comment by lauweijie** [comment]
I think a subdomain for the resource collector would be good though not absolutely necessary. If you're using the Chrome extension, the domain is hidden under the hood once the extension is installed. The bookmarklet shows the domain name in the address bar of the popup dialog.

**Comment by GarthDB** [comment]
yeah. I'll add it to heroku (heroku can support multiple urls)
@lauweijie are there any changes that need to be made to the code itself?

**Comment by lauweijie** [comment]
@GarthDB If the original URL still works then it should be fine.

Once it resolves, we can update these lines:

1. https://github.com/DesignOpen/ResourceCollector/blob/master/gulpfile.js#L69

2. https://github.com/DesignOpen/ResourceCollectorChromeExtension/blob/master/manifest.json#L23

3. https://github.com/DesignOpen/ResourceCollectorChromeExtension/blob/master/src/popup/popup.js#L155

**Comment by GarthDB** [comment]
Closing for now. Might reopen individual items as new issues.
