### ISSUE TITLE
Greetings! Interested in helping out, don't know where to start!

### ISSUE THREAD

**Issue by edouerd** [DesignOpen/designopen.github.io#246]
Hi everyone! Good to meet ya'll.

I'm a designer at IBM, heard about this org via a few colleagues, and have been watching things progress from a distance — decided to finally reach out because I'm interested in helping out, but I don't know how. 

I came into awareness of FOSS culture via physical product design and the onset of 'maker culture', and it wasn't until much later that I discovered the huge world/culture of software-centric open-sourced work.

Specifically I'd love to write/contribute/muse/debate about the physical open source world, implications of open manufacturing, and other cool stuff if the need/interest is there. Let me know how I can help ya'll out!

**Comment by GarthDB** [comment]
Hey @edouerd 

Glad to hear you're interested in helping.

There are a few ways to jump in depending on what you want to start with. Most of it is all detailed in our [CONTRIBUTING.md](https://github.com/DesignOpen/designopen.github.io/blob/master/CONTRIBUTING.md) file.

Feel free to ping us anytime on [Slack](http://slack.opendesign.foundation).
