### ISSUE TITLE
Custom design for Facebook open academy article

### ISSUE THREAD

**Issue by mrondina** [DesignOpen/designopen.github.io#259]

**Comment by mrondina** [comment]
![image](https://cloud.githubusercontent.com/assets/938691/10796288/d9494fec-7d5a-11e5-92ea-63dab6cbcfbc.png)

**Comment by GarthDB** [comment]
![fb_open_academy_2015](https://cloud.githubusercontent.com/assets/125516/10797199/b65eeccc-7d5e-11e5-906c-037ec53b6482.jpg)

**Comment by mrondina** [comment]
What are your thoughts about this direction?
![image](https://cloud.githubusercontent.com/assets/938691/10799462/2fb6ef56-7d6a-11e5-94a4-cf3d7367baa0.png)

**Comment by sishipman** [comment]
![image](https://cloud.githubusercontent.com/assets/15128081/10799518/72a348d2-7d6a-11e5-8403-46345195da48.png)

**Comment by mrondina** [comment]
another variant
![image](https://cloud.githubusercontent.com/assets/938691/10799541/9402a5a4-7d6a-11e5-9423-9241fe5f2e7f.png)

**Comment by sishipman** [comment]
![image](https://cloud.githubusercontent.com/assets/15128081/10799625/fecc08da-7d6a-11e5-96a5-8e95f6611113.png)

**Comment by mrondina** [comment]
I like the color plus Silas' shadow version the best

**Comment by GarthDB** [comment]
![image](https://cloud.githubusercontent.com/assets/125516/10802832/290f9fc4-7d7c-11e5-888d-b403dc6c5b49.png)

![image](https://cloud.githubusercontent.com/assets/125516/10802834/2f246c78-7d7c-11e5-9aaa-d586b08a6006.png)

**Comment by GarthDB** [comment]
![image](https://cloud.githubusercontent.com/assets/125516/10802843/3d1cb204-7d7c-11e5-83cb-bcf30940ca45.png)

**Comment by sishipman** [comment]
![fboa_banner_v2](https://cloud.githubusercontent.com/assets/15128081/10803013/5947ee0c-7d7d-11e5-9a02-75b2e389dd2a.png)
