### ISSUE TITLE
SCSS Refactoring and Linting

### ISSUE THREAD

**Issue by ttimsmith** [DesignOpen/designopen.github.io#273]
I was looking through the stylesheets, and I think there might be some refactoring to do. Eliminating CSS using ID's and maybe use some linting? We could use something like CodeClimate or having a pre-commit hook to lint.

**Comment by GarthDB** [comment]
Sounds awesome. We already have Travis and we could lint there as well.

**Comment by GarthDB** [comment]
Anything you want to jump on? Or just recommending we do it?

**Comment by ttimsmith** [comment]
I figured I could tackle the refactoring first. And create a smaller pull request. If you want, I can simplify the description and title of the issue for just that.

**Comment by GarthDB** [comment]
@ttimsmith that sounds great - so I setup scss-lint with [travis-ci](https://travis-ci.org/DesignOpen/designopen.github.io/builds/123978924) on the [scss-lint branch](https://github.com/DesignOpen/designopen.github.io/tree/scss-lint)

It has a config file ([/.scss-lint.yml](https://github.com/DesignOpen/designopen.github.io/blob/scss-lint/.scss-lint.yml)) but I just turned off all the linters, so that tests pass. I think we could turn on each linter one at a time and then fix the failing lints.  What do you think @ttimsmith?

**Comment by GarthDB** [comment]
@ttimsmith we can chat about it here in the issue or you could jump on slack http://slack.opendesign.foundation/

**Comment by ttimsmith** [comment]
Sure! I put in my email twice, but no invite.

**Comment by AStoker** [comment]
Popping in here. What are you guys using for compiling your code (if at all)? You can easily build in your scss compiling/linting into that process with something like Gulp.

**Comment by GarthDB** [comment]
@astoker we are using Jekyll, it has built in support for SCSS. The real benefit is that it compiles on the server (gh-pages) so people can contribute a new article or new code and we don't have to build it locally before publishing.

**Comment by GarthDB** [comment]
As far as locally checking it, the rake task makes it easy and scss-lint has pretty good editor support. I'm using atom with a scss lint plugin and it will lint the project based on the config file as I go.

**Comment by AStoker** [comment]
Gotcha, gonna look into that, thanks.

**Comment by GarthDB** [comment]
@astoker feel free to poke holes in the build process.

**Comment by GarthDB** [comment]
@ttimsmith I added a bunch of SCSS Linting. I didn't do everything, but good enough for me right now. If you want to add more just open pull requests and/or issues.

**Comment by ttimsmith** [comment]
Wow. You move quick. I was going to get to this in the next few days. I'll take a look when I get back on Tuesday.

**Comment by GarthDB** [comment]
I've been thinking about adding it to the PhoneGap Jekyll sites so this was a great testing ground.
