### ISSUE TITLE
Custom design for Open Design is not Design by Committee 

### ISSUE THREAD

**Issue by GarthDB** [DesignOpen/designopen.github.io#72]
[Open Design is not Design by Committee](http://opendesign.foundation/articles/open-design-is-not-design-by-committee/)

- [x] moodboard
- [x] wireframe
- [x] mockup
- [x] prototype
- [x] publish

**Comment by GarthDB** [comment]
Working on this for the workshop.

**Comment by GarthDB** [comment]
I like the styling on this block quote:
![image](https://cloud.githubusercontent.com/assets/125516/10796815/10203510-7d5d-11e5-8066-a029207091e1.png)

**Comment by GarthDB** [comment]
![image](https://cloud.githubusercontent.com/assets/125516/10796840/25ba491a-7d5d-11e5-93b3-90c986a30743.png)

**Comment by GarthDB** [comment]
I love this line between the image and the content:
![image](https://cloud.githubusercontent.com/assets/125516/10796881/4790b89e-7d5d-11e5-82ac-c2cb78465c64.png)

**Comment by adcolpitts** [comment]
<img width="1426" alt="screen shot 2015-10-28 at 10 44 23 am" src="https://cloud.githubusercontent.com/assets/7290661/10797655/ed0f90d0-7d60-11e5-8467-43d2102593f4.png">

Image is actually a video

**Comment by GarthDB** [comment]
image: https://en.wikipedia.org/wiki/Joint_session_of_the_United_States_Congress#/media/File:Obama_Health_Care_Speech_to_Joint_Session_of_Congress.jpg

**Comment by una** [comment]
I love this thread -- particularly the first layout. The angles are nice but I really like the square-bracket-esque-route. Just my two cents

**Comment by mtsugi** [comment]
Did a quick exploration of how a column structure with pages might work

![type-layout](https://cloud.githubusercontent.com/assets/166028/10802656/4b9d9e7a-7d7b-11e5-8ec0-b9444edd9509.png)

**Comment by mtsugi** [comment]
more pretty pages:
- [Good Magazine](http://magazine.good.is/articles/wikipedia-translation-language-information) Pretty article/type
- [Medium](https://medium.com/message/human-protocol-handshaking-84340025e01d#.8vpz56f07) Pretty article/type
- [Pitchfork cover pages](http://pitchfork.com/features/cover-story/reader/janelle-monae/) interesting work
- [eephus league magazine](http://eephusleague.com/magazine/)
- [polygon xbox one review](http://www.polygon.com/a/xbox-one-review#)
- [NYT Snow Fall](http://www.nytimes.com/projects/2012/snow-fall/#/?part=tunnel-creek)
- [hudl](http://www.hudl.com/) video background
- [Fifty Three - Pencil](http://www.fiftythree.com/pencil) exploding pencil on scroll!
- [NPR](http://www.npr.org/2015/10/28/452014515/the-intense-images-of-afghanistans-long-and-distant-war)

**Comment by mtsugi** [comment]
predictably, the column experiment didn't pan out. It would have required something like CSS regions to get the content to reflow in an intelligent way.
